include ./everforest.conf

font_family Iosevka Nerd Font Mono


transparency = yes
background_opacity 0.7
dynamic_background_opacity yes
font_size 14
enable_audio_bell no

#input_delay 0
#repaint_delay 2
#sync_to_monitor no
#wayland_enable_ime no
