#preload = ~/.config/hypr/wallpaper.jpg
preload = ~/.config/hypr/leaves4.png

#wallpaper = HDMI-A-1,~/.config/hypr/wallpaper.jpg
wallpaper {
    monitor = DP-2
    path=~/.config/hypr/leaves4.png
}
wallpaper {
    monitor = HDMI-A-1
    path=~/.config/hypr/leaves4.png
}

splash = false
